import type { Certification } from "@/types/certification";

export const certifications: Certification[] = [
  // Santander
  {
    id: "santander-ciberseguranca-2025",
    title: "Santander - Cibersegurança 2025",
    institution: "Santander",
    date: "30/11/2025",
    image: "",
    category: "cybersecurity",
  },
  {
    id: "santander-ciberseguranca",
    title: "Introdução à Cibersegurança com o Santander",
    institution: "Santander",
    date: "30/09/2025",
    image: "",
    category: "cybersecurity",
  },

  // Rocketseat
  {
    id: "rocketseat-redes-neurais",
    title: "Redes Neurais",
    institution: "Rockeseat",
    date: "27/01/2026",
    image: "",
    category: "neuralnetworks"
  },
  
  // DIO - Cibersegurança
  {
    id: "dio-exploracao-vulnerabilidades",
    title: "Exploração de Vulnerabilidades e Ataques",
    institution: "DIO",
    date: "30/11/2025",
    image: "",
    category: "cybersecurity",
  },
  {
    id: "dio-malware-python",
    title: "Simulando um Malware de Captura de Dados Simples em Python e Aprendendo a se Proteger",
    institution: "DIO",
    date: "30/11/2025",
    image: "",
    category: "cybersecurity",
  },
  {
    id: "dio-busca-vulnerabilidades-invasao",
    title: "Fundamentos de Busca por Vulnerabilidades e Testes de Invasão",
    institution: "DIO",
    date: "30/11/2025",
    image: "",
    category: "cybersecurity",
  },
  {
    id: "dio-ataque-brute-force",
    title: "Simulando um Ataque de Brute Force de Senhas com Medusa e Kali Linux",
    institution: "DIO",
    date: "30/11/2025",
    image: "",
    category: "cybersecurity",
  },
  {
    id: "dio-pentest",
    title: "PenTest: Principais Conceitos e Ferramentas",
    institution: "DIO",
    date: "28/11/2025",
    image: "",
    category: "cybersecurity",
  },
  {
    id: "dio-man-in-the-middle",
    title: "Man in the Middle: Ataques e Mitigações",
    institution: "DIO",
    date: "28/11/2025",
    image: "",
    category: "cybersecurity",
  },
  {
    id: "dio-pos-exploracao",
    title: "Pós-Exploração em Sistemas Comprometidos",
    institution: "DIO",
    date: "28/11/2025",
    image: "",
    category: "cybersecurity",
  },
  {
    id: "dio-tecnicas-exploracao",
    title: "Técnicas de Exploração de Vulnerabilidades",
    institution: "DIO",
    date: "28/11/2025",
    image: "",
    category: "cybersecurity",
  },
  {
    id: "dio-enumeracao-exploracao",
    title: "Princípios de Enumeração e Exploração de Vulnerabilidades",
    institution: "DIO",
    date: "28/11/2025",
    image: "",
    category: "cybersecurity",
  },
  {
    id: "dio-engenharia-social-topicos",
    title: "Tópicos em Engenharia Social",
    institution: "DIO",
    date: "28/11/2025",
    image: "",
    category: "cybersecurity",
  },
  {
    id: "dio-engenharia-social-hackers",
    title: "Engenharia Social: Como os Hackers Usam a Mente Humana para Invasões Digitais",
    institution: "DIO",
    date: "28/11/2025",
    image: "",
    category: "cybersecurity",
  },
  {
    id: "dio-coleta-analise-seguranca",
    title: "Introdução à Coleta e Análise de Segurança Cibernética",
    institution: "DIO",
    date: "28/11/2025",
    image: "",
    category: "cybersecurity",
  },
  {
    id: "dio-testes-invasao-pentest",
    title: "Fundamentos de Testes de Invasão (Pentest)",
    institution: "DIO",
    date: "28/11/2025",
    image: "",
    category: "cybersecurity",
  },
  {
    id: "dio-fundamentos-ciberseguranca",
    title: "Fundamentos de Cibersegurança",
    institution: "DIO",
    date: "28/11/2025",
    image: "",
    category: "cybersecurity",
  },
  {
    id: "dio-deep-web",
    title: "Introdução à Deep Web e Anonimato",
    institution: "DIO",
    date: "28/11/2025",
    image: "",
    category: "cybersecurity",
  },
  {
    id: "dio-principios-ciberseguranca",
    title: "Princípios da Cibersegurança",
    institution: "DIO",
    date: "30/09/2025",
    image: "",
    category: "cybersecurity",
  },
  
  // DIO - Redes
  {
    id: "dio-varredura-rede",
    title: "Conceitos e Técnicas de Varredura de Rede",
    institution: "DIO",
    date: "28/11/2025",
    image: "",
    category: "networking",
  },
  {
    id: "dio-redes-computadores",
    title: "Fundamentos de Redes de Computadores",
    institution: "DIO",
    date: "28/11/2025",
    image: "",
    category: "networking",
  },
  
  // DIO - Desenvolvimento
  {
    id: "dio-portfolio-projetos",
    title: "Desafios de Projetos: Crie Um Portfólio Vencedor",
    institution: "DIO",
    date: "28/11/2025",
    image: "",
    category: "development",
  },
  {
    id: "dio-desafios-codigo",
    title: "Desafios de Código: Aperfeiçoe Sua Lógica e Pensamento Computacional",
    institution: "DIO",
    date: "28/11/2025",
    image: "",
    category: "development",
  },
  
  // DIO - Outros
  {
    id: "dio-sistemas-operacionais",
    title: "Conceitos e Práticas de Sistemas Operacionais e Máquinas Virtuais",
    institution: "DIO",
    date: "28/11/2025",
    image: "",
    category: "other",
  },
  {
    id: "dio-onboarding",
    title: "Prepare-se Para a Jornada (Onboarding)",
    institution: "DIO",
    date: "30/09/2025",
    image: "",
    category: "other",
  },
  
  // Microsoft & Azure
  {
    id: "microsoft-fabric",
    title: "Certificado Microsoft Fabric",
    institution: "Microsoft",
    date: "11/07/2025",
    image: "",
    category: "cloud",
  },
  {
    id: "azure-big-data",
    title: "Certificado Azure Big Data",
    institution: "Udemy",
    date: "30/04/2025",
    image: "",
    category: "cloud",
  },
  
  // Deal Group
  {
    id: "deal-ia-centric",
    title: "Introdução à Experiência AI Centric .NET com a Deal Group",
    institution: "Deal Group",
    date: "23/07/2025",
    image: "",
    category: "development",
  },
  {
    id: "deal-intro-dotnet",
    title: "Introdução Deal Intro .NET",
    institution: "Deal Group",
    date: "23/07/2025",
    image: "",
    category: "development",
  },
  
  // Rocketseat - NLW
  {
    id: "nlw-nodejs",
    title: "Certificado NLW NodeJS",
    institution: "Rocketseat",
    date: "30/04/2025",
    image: "",
    category: "development",
  },
  {
    id: "nlw-python",
    title: "Certificado NLW Python",
    institution: "Rocketseat",
    date: "30/04/2025",
    image: "",
    category: "development",
  },
  {
    id: "nlw-react",
    title: "Certificado NLW React",
    institution: "Rocketseat",
    date: "30/04/2025",
    image: "",
    category: "development",
  },
  {
    id: "nlw-react-native",
    title: "Certificado NLW React Native",
    institution: "Rocketseat",
    date: "30/04/2025",
    image: "",
    category: "development",
  },
  
  // PyStack Week
  {
    id: "pystack-week-9",
    title: "Certificado PyStack Week 9.0",
    institution: "PyStack",
    date: "30/04/2025",
    image: "",
    category: "development",
  },
];
